Accounts/urls.py
from django.urls import path
from .views import user_login, user_signup, user_logout

app_name = 'users'

urlpatterns = [
    path('login', user_login, name='login'),
    path('signup', user_signup, name='signup'),
    path('logout', user_logout, name='logout'),
]

Meaning/urls.py
from django.urls import path
from .views import search, save, show_words

app_name = 'Meanings'

urlpatterns = [
    path('search', search, name='search'),
    path('save', save, name='save'),
    path('words', show_words, name='words'),
]

Pages/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home),
]

Practice/urls.py
from django.urls import path
from .views import home, result

app_name = 'practice'

urlpatterns = [
    path('', home, name='home'),
    path('result', result, name='result'),
]

Share/urls.py
from django.urls import path
from .views import groups, not_joined, join_group, detail_group_user, detail_group_wordwall, create_post, list_posts, detail_post, comment_like, user_detail

app_name = 'share'

urlpatterns = [
    path('groups', groups, name='groups'),
    path('notjoined', not_joined, name='not_joined'),
    path('join/<int:pk>', join_group, name='join_group'),
    path('detail/users/<int:pk>', detail_group_user, name='detail_group_user'),
    path('detail/wordwall/<int:pk>', detail_group_wordwall, name='detail_group_wordwall'),
    path('detail/user/personal/<int:pk>', user_detail, name='user_detail'),
    path('post/create/<int:pk>', create_post, name="create_post"),
    path('post/listings/<int:pk>', list_posts, name="list_posts"),
    path('post/detail/<int:pk>', detail_post, name="detail_post"),
    path('post/comment/like/<int:cpk>/<int:ppk>', comment_like, name="comment_like"),
]

Vocab/urls.py
from django.contrib import admin
from django.urls import path, include
import Pages, Meaning, Share, Practice, Accounts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Pages.urls')),
    path('meaning', include('Meaning.urls', namespace='meaning')),
    path('share/', include('Share.urls', namespace='share')),
    path('practice/', include('Practice.urls', namespace='practice')),
    path('users/', include('Accounts.urls', namespace='users')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Practice/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Score(models.Model):
    score = models.IntegerField(blank=True)
    total = models.IntegerField(blank=True)
    user = models.ManyToManyField(User, blank=True)
    added = models.DateTimeField(auto_now_add=True)
    percent = models.IntegerField(blank=True)

    class Meta:
        ordering = ['-added']

Practice/views.py
from django.shortcuts import render
import ast
from random import shuffle
from .models import Score
import random

# Create your views here.
def shuffle_list(lst):
    lst2 = lst.copy()
    shuffle(lst2)
    return lst2

def home(request):
    user = request.user
    context = {}
    context['show'] = True
    if user.is_active:
        if request.method == 'POST':
            if request.POST['number']:
                num = request.POST['number']
                context['show'] = False
                context['number'] = num
                words = user.word_set.all()
                all_words = []
                for word in words:
                    meaning = []
                    temp = ''
                    for mean in word.meaning_set.all():
                        temp = mean.pos
                        meaning.append((ast.literal_eval(mean.meaning), temp))
                    all_words.append((word, meaning))
                k = shuffle_list(all_words)[:int(num)]
                context['words'] = k
                context['total_number'] = len(k)
    return render(request, 'practice.html', context)

motivation = ["All our dreams can come true, if we have the courage to pursue them.” – Walt Disney",
"“The secret of getting ahead is getting started.” – Mark Twain",
"“I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life and that is why I succeed.” – Michael Jordan",
"“Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.” – Mary Kay Ash",
"“The best time to plant a tree was 20 years ago. The second best time is now.” – Chinese Proverb",
"“Only the paranoid survive.” – Andy Grove",
"“It’s hard to beat a person who never gives up.” – Babe Ruth",
"“I wake up every morning and think to myself, ‘how far can I push this company in the next 24 hours.’” – Leah Busque",
"“If people are doubting how far you can go, go so far that you can’t hear them anymore.” – Michele Ruiz",
"“We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success.” – Arianna Huffington",
"“Write it. Shoot it. Publish it. Crochet it, sauté it, whatever. MAKE.” – Joss Whedon"
]
def result(request):
    user = request.user
    context = {}
    user = request.user
    if user.is_active:
        if request.method == 'POST':
            score = request.POST['score_input']
            total = request.POST['max-score']
            score = int(score)
            total = int(total)
            context['score'] = score
            context['total'] = total
            obj, created = Score.objects.get_or_create(score=score, total=total, percent=(score*100)/total)
            obj.user.add(user)
            context['history'] = user.score_set.all()
            ind = random.randint(0,len(motivation))
            context['quote'] = motivation[ind]
    return render(request, 'result.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vocabulary</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#">Vocabulary Builder</a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href={% url 'meaning:search'%}>Search Meaning</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href={% url 'meaning:words'%}>Saved Words</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href={% url 'share:groups'%}>Groups</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href={% url 'practice:home'%}>Practice</a>
            </li>
            {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <a type="button" href="" class="btn btn-success">Welcome, {{user | title}}</a>
                <a type="button" href={% url 'users:logout' %} class="btn btn-info ml-3">Logout</a>
            {% else %}
                <a type="button" href={% url 'users:login' %} class="btn btn-success">Please Log In For More Features</a>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        <div class="links mt-5">
            {% block button %}
            {% endblock%}
        </div>
        
    </div>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script>
    
        const users = () => {document.getElementbyId('users-btn').addEventListener('click', (event) => {
            document.getElementbyId('users').style.display = 'inline';
            document.getElementbyId('word-wall').style.display = 'None';
        })};

        const wordwall = () => {document.getElementbyId('wordwall-btn').addEventListener('click', (event) => {
            document.getElementbyId('word-wall').style.display = 'inline';
            document.getElementbyId('users').style.display = 'None';
        })};

    </script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/create_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <div class="form-group">
        <label for="FormControlInput">Title</label>
        <input type="text" name="title" class="form-control" id="FormControlInput">
    </div>
    <div class="form-group" id="form">
        <div id='image-form'>
        <label>Image</label>
        <br>
        <input type="file" name="image-1">
        <br>
        </div>
        <button type="button" id="add-image" class="btn btn-info btn-sm mt-3 mb-3">Add Image Field</button>
    </div>
    <div class="form-group">
    <label for="Textarea1">Article</label>
    <textarea class="form-control" name="text" id="Textarea1" rows="5"></textarea>
    </div>
    <div class="form-group" align="center">
    <button type="submit" class="btn btn-primary">Post</button>
    {% comment %} <a href={% url 'share:list_posts' group %}><button type="button" class="btn btn-success">Show Posts</button></a> {% endcomment %}
    </div>
    </form>

</div>

<script>

let i = 1
document.getElementById('add-image').addEventListener('click', (event) => {
    i += 1
    if (i < 6) {
        document.getElementById('image-form').innerHTML += ` 
        <br>
            <input type="file" name="image-${i}">
        <br>`
        event.preventDefault
    } else {
        document.getElementById('form').innerHTML += `
        <div class="alert alert-danger" role="alert">
            Image Limit Reached 
        </div> 
        `
    }
})

</script>
{% endblock %}

templates/form.html
{% extends 'base.html' %}

{% block button %}
    <div align="center">
    <a href="{% url 'meaning:search'%}" class="btn btn-info ml-5 disabled" role="button" >Search Meanings</a>
    <a href={% url 'meaning:words'%} class="btn btn-primary ml-5"  role="button">My Words</a>
    </div>
{% endblock %}

{% block content %}
    <div class="form" align="center">
        <form action="{% url 'meaning:search' %}" method="POST">
            {% csrf_token %}
            <div class="form-group col-md-10 mx-auto mt-5">
                <label for="term">Search Term</label>
                <input type="text" name="term" class="form-control" required>
                <input type="Submit" class="btn btn-secondary mt-2"> 
            </div>
        </form>
    </div>

    {% if save %}
        {% if saved %}
            <div class="alert alert-success col-md-5 mx-auto" role="alert">
                The word was saved successfully.
            </div>
        {% else %}
            <div class="alert alert-danger col-md-5 mx-auto" role="alert">
                Word is already present in the database.
            </div>
        {% endif %}
    {% endif %}


    {% comment %} {% if term %}
        <h3>
            {{ term }}
        </h3>
    {% endif %} {% endcomment %}
    {% if similar %}
        <div class="card text-white bg-dark mb-3 col-md-5 mx-auto">
        <div class="card-header text-center"><h4>{{term}}</h4></div>
            <div class="card-body">
                <h4 class="card-title">{{title}}</h4>
                {% if definition %}
                    {% for d in definition %}
                        <div class="definition">
                            <b>{{d.0}}</b>:
                            <ul>
                                {% for i in d.1 %}
                                    <li>{{i}}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                {% endif %}
                <h3 style='text-align: center;' class="mb-3">Similar Words: </h3>
                <div class="d-flex flex-wrap justify-content-around">
                    {% for item in similar %}
                        <span class="badge badge-info mt-1 pd-3" style="font-size: 1em;">{{item.word}}</span>
                    {% endfor %}
                </div>
                <hr>
                <form action="{% url 'meaning:save' %}" method="POST">
                    {% csrf_token %}
                    <input type="term" name="term" value={{term}} hidden />
                    <label for="term">Add Note</label>
                    <input type="text" name="text" class="form-control mb-3">
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
        {% comment %} {% for term in similar %}
            <h1>{{term}}</h1>
        {% endfor %} {% endcomment %}
    {% endif %}
{% endblock %}

templates/group_detail_user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">

    <div class="col-md-10 mx-auto">
        <h1 class="border border-success p-2 rounded-pill text-center">{{group.name}}</h1>
    </div>

    <div class="col-md-10 mx-auto buttons mt-5" align="center">
        <a href="{% url 'share:detail_group_user' group_id %}" id="users-btn" class="btn btn-outline-success col-md-3 disabled">Users</a>
        <a href="{% url 'share:list_posts' group_id %}" class="btn btn-outline-dark col-md-3 ml-5">Posts</a>
        <a href="{% url 'share:detail_group_wordwall' group_id %}" id="wordwall-btn" class="btn btn-outline-info col-md-3 ml-5">Word Wall</a>
    </div>

<div class="mt-5" style="width: 100%"><h1 align="center">Users</h1></div>
<div class="row">
{% for user in users %}
  <div class="col-sm-4 mt-5" align="center">
    <div class="card border-primary">
      <div class="card-body">
        <h5 class="card-title">{{user.0}}</h5>
        <p class="card-text">Number of Users: {{user.1}}</p>
        <a href={% url 'share:user_detail' user.0.id%} class="btn btn-info">Show More</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

{% block script %}
    <script type="application/javascript" src="{% static 'detail.js' %}"></script>
{% endblock %}

templates/group_detail_wordwall.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
    <div class="col-md-10 mx-auto">
        <h1 class="border border-success p-2 rounded-pill text-center">{{group.name}}</h1>
    </div>

    <div class="col-md-10 mx-auto buttons mt-5" align="center">
        <a href="{% url 'share:detail_group_user' group_id %}" id="users-btn" class="btn btn-outline-success col-md-3">Users</a>
        <a href="{% url 'share:list_posts' group_id %}" class="btn btn-outline-dark col-md-3 ml-5">Posts</a>
        <a href="{% url 'share:detail_group_wordwall' group_id %}" id="wordwall-btn" class="btn btn-outline-info col-md-3 ml-5 disabled">Word Wall</a>
    </div>

    <div id="word-wall">
    <div class="mt-5" style="width: 100%"><h1 align="center">Word Wall</h1></div>
    <div class="container mt-5 mx-auto card-columns">
        {% for word in words %}
            <div class="card text-white bg-dark mx-auto" style="oveflow:hidden;">
                <div class="card-header text-center"><h3>{{word.0}}</h3></div>
                <div class="card-body">
                    <ul>
                    {% for key in word.1 %}
                        <b>{{key.1}}</b>
                        {% for k in key.0 %}
                            <li>{{k}}</li>
                        {% endfor %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
    </div>
{% endblock %}

{% block script %}
    <script type="application/javascript" src="{% static 'detail.js' %}"></script>
{% endblock %}

templates/groups.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-10 mx-auto mb-5" align="center">
        <a href={% url 'share:not_joined' %} class="btn btn-outline-dark col-md-5 mx-auto " role="button" >Groups That You Don't Follow</a>
        <br>
        <a href="#" class="btn btn-info col-md-5 mx-auto mt-3" role="button" >Create a new Group</a>
        {% if groups %}
        <div class="members mt-5">
            <div class="text-center">
                <h1 class="mb-5">
                    Groups That You Follow
                </h1>
                    <div class="row">
                        {% for group in groups %}
                            <div class="col-sm-4">
                                <div class="card border-success mt-4">
                                    <div class="card-body">
                                        <h5 class="card-title">{{group.0}}</h5>
                                        <p class="card-text">Number Of Users: {{group.1}}</p>
                                        <a href="{% url 'share:detail_group_user' group.0.id %}" class="btn btn-primary">Show More</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <h2> No Groups </h2>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/listings.html
{% extends 'base.html'%}

{% block button %}
    <a href="{% url 'meaning:search'%}" class="btn btn-info ml-5" role="button" >Search Meanings</a>
    <a href={% url 'meaning:words'%} class="btn btn-primary ml-5 disabled"  role="button">My Words</a>
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="container mt-5 mx-auto card-columns">
            {% for word in words %}
                <div class="card text-white bg-dark mx-auto" style="oveflow:hidden;">
                    <div class="card-header text-center"><h3>{{word.0}}</h3></div>
                    <div class="card-body">
                        {% for key in word.1 %}
                        <h4 class="card-title">{{key.0}}</h4>
                        <ul>
                        {% for mean in key.1%}
                            <li>{{mean}}</li>
                        {% endfor %}
                        </ul>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1> Please Log In </h1>
    {% endif %}


{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<div align="center" class="col-md-5 mx-auto mt-5 border border-info p-5 rounded">
    {% if error %}
    <div class="alert alert-danger" role="alert">
        Login Credentials did not match. Please Try Again.
    </div>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="username" class="form-control" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password">
        </div>
        <button type="submit" class="btn btn-info">Login</button>
    </form>
</div>
<div class="center col-md-10 mx-auto mt-5 mb-5" align="center"><a class="btn btn-primary" href={% url 'users:signup' %} role="button">SignUp Here</a></div>
 </div>
{% endblock %}

templates/post-detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

<div class="div text-center mb-5">
    <h1>{{post.title | title}}</h1>
</div>


<div class="row">
    {% for image in images %}
        <div class="col-md-4">
           <img class="card-img-top" src="{{image.image.url}}" alt="Card image cap">
        </div>
    {% endfor %}
</div>

<div class="mt-5">
<p>{{post.text}}</p>
</div>

<div class="mt-5 form-div mb-5">
    <form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="textArea">What do you feel about this post?</label>
        <textarea class="form-control" name="comment" id="textArea" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-outline-success">Submit</button>
    </form>
</div>

<div class="mt-5" align="center">
{% for comment in comments %}
    <div class="card border-success m-5">
    <div class="card-header">
        {{comment.user}}
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
        <p>{{comment.content}}</p>
        <form action={% url 'share:comment_like' comment.id post.id %} method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-info">
                Likes <span class="badge badge-light">{{comment.likes.count}}</span>
            </button>
        </form>
        </blockquote>
    </div>
    </div>
{% endfor %}
</div>

</div>


{% endblock %}

templates/post-listings.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <div class="col-md-10 mx-auto">
        <h1 class="border border-success p-2 rounded-pill text-center">{{group.name}}</h1>
    </div>

    <div class="col-md-10 mx-auto buttons mt-5" align="center">
        <a href="{% url 'share:detail_group_user' group.id %}" id="users-btn" class="btn btn-outline-success col-md-3">Users</a>
        <a href="{% url 'share:list_posts' group.id %}" class="btn btn-outline-dark col-md-3 ml-5 disabled">Posts</a>
        <a href="{% url 'share:detail_group_wordwall' group.id %}" id="wordwall-btn" class="btn btn-outline-info col-md-3 ml-5">Word Wall</a>
    </div>

    <div class="col-md-12 mx-auto" align="center">
        <a href="{% url 'share:create_post' group.id %}" id="create_post" class="btn btn-info col-md-3 mt-5">Create Post</a>
    </div>

    {% if posts %}
        <div class="row row-cols-1 row-cols-md-3 mt-5 text-center">
        {% for post in posts %}
            <div class="col mb-4">
                <div class="card border border-success rounded">
                    <img src="{{post.1.image.url}}" class="card-img-top p-3" alt="ArticleImage">
                <div class="card-body">
                    <h5 class="card-title">{{post.0.title}}</h5>
                    <p class="card-text">{{post.2}}</p>
                    <form method="POST">
                        {% csrf_token %}
                        <input type="number" class="d-none" id="id" value={{post.0.id}}>
                        <button type="submit" id="like" class="btn btn-info mt-2">{{post.3}} Likes</button>
                        <a href={% url 'share:detail_post' post.0.id%}><button type="button" class="btn btn-dark ml-3 mt-2">Go To Post</button></a>
                    </form>
                </div>
            </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
    <div class="col-md-12 mt-5" align="center">
        <h1>Not Posts Yet</h1>
        <a href={% url 'share:create_post' group.id %}><button type="button" class="btn btn-outline-info col-md-5 mt-5">Create A Post!</button></a>
    </div>
    {% endif %}

</div>

<script>
const like_btns = document.querySelectorAll('#like')
for (const item of like_btns) {
    item.addEventListener('click', (event) => {
        console.log(event.path[2].childNodes[5].childNodes[3].name="index")
    })
}
</script>

{% endblock %}

templates/practice.html
{% extends 'base.html'%}

{% block content %}

    {% if user.is_authenticated %}
        {% if show %}
        <div class="container">
            <div class="text-center">
                <h1>Enter the number of words you want to practice with</h1>
                <form class="mt-5 col-mb-3 offset-md-6 mx-auto" method="post">
                    {% csrf_token %}
                    <label for="term">Number of Words</label>
                    <input type="number" min="0" max="30" name="number" class="form-control mb-3">
                    <button type="submit" id="start" class="btn btn-info mt-2">Start Test</button>
                </form>
            </div>
        </div>
        {% else %}
            <div class="container">
                <h1 class="text-center">
                    Words
                </h1>
                <h3 class="text-center" id="score">
                    Score: 0
                </h3><br>
                <div class="words-container card-columns">
                    {% for word in words %}
                    <div class="card text-white bg-dark mx-auto" style="oveflow:hidden;">
                        <div class="card-header text-center"><h3>{{word.0}}</h3></div>
                            <div class="card-body d-none">
                                <ul>
                                    {% for key in word.1 %}
                                    <b>{{key.1}}</b>
                                    {% for k in key.0 %}
                                    <li>{{k}}</li>
                                    {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="text-center">
                            <a type="button" class="btn btn-secondary mb-3 mt-3 ml-5 mr-5 show-meaning" style='display: block;'>Show Meaning</a>
                            <a type="button" class="btn btn-info mb-3 mt-2 known">Know</a>
                            <a type="button" class="btn btn-info ml-3 mb-3 mt-2 unknown">Don't Know</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="proceed mt-3" align="center">  
                <form name="proceed" action={% url 'practice:result' %} method="POST">
                    {% csrf_token %}
                    <input type="text" name="score_input" id='score-input' class="score-input d-none">
                    <input type="number" name="max-score" id='max-score' class="max-score d-none" value={{total_number}}>
                    <button type="submit" id="score-btn" class="btn btn-success col-md-8 mb-5 mt-2">Proceed</button>
                </form>
            </div>
        {% endif %}
    {% else %}
        <div class="text-center">
            <h1>
                Please Login to Continue
            </h1>
        </div>
    {% endif %}

<script>

    score = 0

    const shows = document.querySelectorAll('.show-meaning')
    
    for (const show of shows) {
        show.addEventListener('click', (event) => {
            console.log(event.path[2].childNodes[3].className)
            if (event.path[2].childNodes[3].className == 'card-body') {
                event.path[2].childNodes[3].className = 'card-body d-none';
                event.target.innerText = 'Show Meaning';
            } else {
                event.path[2].childNodes[3].className = 'card-body';
                event.target.innerText = 'Hide Meaning';
            }
            event.preventDefault();
        })
    }

    const knowns = document.querySelectorAll('.known')
    for (const item of knowns) {
        item.addEventListener('click', (event) => {
            console.log(event)
            if (event.path[2].className.includes("unknown")) {
                console.log(event.path[2].className)
                score += 2
                document.getElementById('score').innerText = `Score: ${score}`
            } else if (event.path[2].className == "card text-white bg-dark mx-auto") {
                score += 1
                document.getElementById('score').innerText = `Score: ${score}`
            }
            event.path[2].style = "border-color: #22a7f0; border-style: solid; border-width: thick;";
            event.path[2].className = "card text-white bg-dark mx-auto known";
        })
    }


    const unknowns = document.querySelectorAll('.unknown')
    for (const item of unknowns) {
        item.addEventListener('click', (event) => {
            if (!event.path[2].className.includes("unknown") && event.path[2].className.includes("known")) {
                score -= 2
                document.getElementById('score').innerText = `Score: ${score}`
            } else if (event.path[2].className == "card text-white bg-dark mx-auto") {
                score -= 1
                document.getElementById('score').innerText = `Score: ${score}`
            }
            event.path[2].style = "border-color: #f15a22; border-style: solid; border-width: thick;";
            event.path[2].className = "card text-white bg-dark mx-auto unknown"
        })
    }

    document.getElementById('score-btn').addEventListener('click', (event) => {
        document.getElementById('score-input').value = `${score}`
    })

</script>
{% endblock %}

templates/unfollowed_groups.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-10 mx-auto" align="center">
        <a href={% url 'share:groups' %} class="btn btn-outline-dark col-md-5 mx-auto mb-3" role="button" >Groups That You Follow</a>
        <br>
        <a href="#" class="btn btn-info col-md-5 mx-auto" role="button" >Create a new Group</a>
        <h1 class="mt-5" style="text-align: center;"> Groups You Don't Follow </h1>
        <div class="members mt-5">
            <div class="text-center">
                {% if groups %}
                    <div class="row">
                        {% for group in groups %}
                            <div class="col-sm-4">
                                <div class="card border-success mt-4">
                                    <div class="card-body">
                                        <h5 class="card-title">{{group.0}}</h5>
                                        <p class="card-text">Number Of Users: {{group.1}}</p>
                                        <a href="{% url 'share:join_group' group.0.id %}" class="btn btn-info">Click To Join</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <h2> No Groups </h2>
                {% endif %}
            </div>
        </div>
    </div>
    

{% endblock %}